### ISSUE TITLE
Issue about source of "v3det_coco.json"

### ISSUE THREAD

**Issue by fujiawei0724** [mlvlab/RALF#2]
Thanks for the great work. I have a tiny issue about the source of the json file "v3det_coco.json", I want to know how you get this file? Looking forward to your help.

**Comment by parang99** [comment]
Thank you for your interest. The `v3det_coco.json` file is created by removing COCO categories from V3Det's vocabulary. We manually performed this filtering process to prevent cheating before using V3Det as the vocabulary set.
